sudo: false
language: java
jdk:
- oraclejdk8
deploy:
  provider: releases
  api_key: "45769e11cb443f01148ace5b949bb6b9b0b7a743"
  file: "target/gs-rest-hateoas-0.1.0.jar"
  skip_cleanup: true
  on:
    tags: true

